services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYTHONPATH: /app
      POSTGRES_HOST: db
    volumes:
      - .:/app
    command: >
      sh -c "
      while ! nc -z db 5432; do sleep 2; done &&
      PGPASSWORD=$POSTGRES_PASSWORD psql -h db -U $POSTGRES_USER -d $POSTGRES_DB -c 'CREATE EXTENSION IF NOT EXISTS vector' &&
      alembic upgrade head &&
      uvicorn rag_project.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge