"""sources.source_path

Revision ID: 3b4527395334
Revises: 79854ef7a2b6
Create Date: 2025-06-17 00:15:01.221299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4527395334'
down_revision: Union[str, None] = '79854ef7a2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('source_path', sa.String(length=500), nullable=False))
    op.drop_constraint(op.f('sources_path_to_content_key'), 'sources', type_='unique')
    op.drop_index(op.f('idx_source_path'), table_name='sources')
    op.create_index('idx_source_path', 'sources', ['source_path'], unique=False)
    op.create_unique_constraint(None, 'sources', ['source_path'])
    op.drop_column('sources', 'path_to_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('path_to_content', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sources', type_='unique')
    op.drop_index('idx_source_path', table_name='sources')
    op.create_index(op.f('idx_source_path'), 'sources', ['path_to_content'], unique=False)
    op.create_unique_constraint(op.f('sources_path_to_content_key'), 'sources', ['path_to_content'], postgresql_nulls_not_distinct=False)
    op.drop_column('sources', 'source_path')
    # ### end Alembic commands ###
